"""Cited document drafts (roadmap S8).

Templates for the paperwork an Ayurveda formulation actually needs on the way to
a filing. Each draft is filled from the matter's formulation profile and, for
every legal assertion it makes, carries a **[Legal basis: …]** marker resolved —
where the corpus supports it — to a real retrieved section. Nothing here is an
LLM generation: the structure is fixed, only the matter's own facts and the
grounded citations vary.

Drafts are skeletons for a professional to complete and verify — never a
ready-to-file document.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone

from app.core.logging import get_logger
from app.schemas import Citation, DraftKind, DraftKindInfo, Matter
from app.services.checklist import _ground

logger = get_logger(__name__)


KIND_INFO: dict[DraftKind, DraftKindInfo] = {
    DraftKind.form1: DraftKindInfo(
        kind=DraftKind.form1,
        title="Patent application — Form 1 (skeleton)",
        description="Application for grant of a patent under the Patents Act, "
        "1970. Pre-fills the invention title and the biological-source "
        "declarations from the matter.",
    ),
    DraftKind.nba_abs: DraftKindInfo(
        kind=DraftKind.nba_abs,
        title="NBA approval / intimation for IP on a biological resource",
        description="Application to the National Biodiversity Authority before "
        "applying for IP based on a biological resource obtained from India.",
        requires_abs=True,
    ),
    DraftKind.disclosure_of_source: DraftKindInfo(
        kind=DraftKind.disclosure_of_source,
        title="Declaration of source & geographical origin of biological material",
        description="The mandatory disclosure of the source and geographical "
        "origin of biological material used in the invention.",
    ),
    DraftKind.s3p_rebuttal: DraftKindInfo(
        kind=DraftKind.s3p_rebuttal,
        title="Argument: not excluded under Section 3(p) / 3(e)",
        description="A reasoned submission that the claimed invention is not "
        "traditional knowledge or a mere admixture, for an examination reply.",
    ),
}

_DISCLAIMER = (
    "> **Draft skeleton — not a filing.** Generated by IP-SAKTI Sahayak from the "
    "matter's formulation profile. Every legal basis marker must be checked "
    "against the official section text. Complete the bracketed fields and have a "
    "registered patent agent / legal professional review before use. This is "
    "not legal advice."
)


@dataclass
class RenderedDraft:
    kind: DraftKind
    title: str
    markdown: str
    citations: list[Citation]


class _Grounder:
    """Resolve a legal-basis probe to a real citation, once per probe."""

    def __init__(self, jurisdiction: str) -> None:
        self._j = jurisdiction
        self._cache: dict[str, Citation | None] = {}
        self.used: list[Citation] = []

    def basis(self, claim: str, probe: str) -> str:
        """Return a '[Legal basis: …]' marker, grounded if the corpus supports it."""
        if probe not in self._cache:
            hits = _ground(probe, self._j)
            self._cache[probe] = hits[0] if hits else None
        cite = self._cache[probe]
        if cite is None:
            return f"  \n_[Legal basis: {claim} — verify the governing provision]_"
        if not any(
            c.source == cite.source and c.section == cite.section for c in self.used
        ):
            self.used.append(cite)
        stale = f" ⚠ may be amended by {cite.amended_by}" if cite.amended_by else ""
        return (
            f"  \n_[Legal basis: {cite.source}, Section {cite.section}{stale}]_"
        )


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _profile_lines(matter: Matter) -> list[str]:
    p = matter.profile
    return [
        f"- **Formulation:** {matter.formulation_label or 'not classified'}",
        f"- **Dosage form:** {p.dosage_form or '[dosage form]'}",
        "- **Key ingredients:** "
        + (", ".join(p.key_ingredients) if p.key_ingredients else "[ingredients]"),
        f"- **Intended use / claims:** {p.intended_use or '[intended use]'}",
        f"- **Asserted novelty:** {p.process_novelty or '[what is new]'}",
        f"- **Biological source / origin:** {p.source_notes or '[source and geographical origin]'}",
    ]


def _header(matter: Matter, title: str) -> list[str]:
    return [
        f"# {title}",
        "",
        _DISCLAIMER,
        "",
        f"**Matter:** {matter.title}  ",
        f"**Generated:** {_now()}  ",
        f"**Jurisdiction:** {matter.jurisdiction.value}",
        "",
        "## Formulation particulars",
        "",
        *_profile_lines(matter),
        "",
    ]


def _traceability(g: _Grounder) -> list[str]:
    out = ["", "## Traceability — legal bases cited", ""]
    if not g.used:
        out.append(
            "_No provision in the corpus met the citation bar for this draft. "
            "Each legal-basis marker above must be verified manually._"
        )
        return out
    for c in g.used:
        url = f" — {c.source_url}" if c.source_url else ""
        as_of = f" (text as of {c.as_of})" if c.as_of else ""
        amended = (
            f"  \n  ⚠ may have been amended by {c.amended_by}" if c.amended_by else ""
        )
        out.append(f"- {c.source}, Section {c.section}{as_of}{url}{amended}")
    return out


# --------------------------------------------------------------------------- #
# Templates
# --------------------------------------------------------------------------- #
def _form1(matter: Matter, g: _Grounder) -> list[str]:
    p = matter.profile
    title = p.intended_use or matter.formulation_label or "[title of the invention]"
    body = [
        "## Form 1 — Application for grant of a patent",
        "_(Patents Act, 1970 / Patents Rules, 2003 — Form 1)_",
        "",
        "1. **Applicant(s):** [name, nationality, address]",
        "2. **Category of applicant:** [natural person / startup / small entity / others]",
        f"3. **Title of the invention:** {title}"
        + g.basis("a patent application must state the invention",
                  "application for grant of patent form contents"),
        "4. **Inventor(s):** [names and addresses; attach Form 5 declaration]",
        "5. **Priority / earlier application particulars:** [none / details]",
        "",
        "### Declarations",
        "",
        "- The applicant is in possession of the invention."
        + g.basis("the applicant must be entitled to apply",
                  "who may apply for a patent true and first inventor"),
        "- A complete specification with claims and an abstract is filed herewith."
        + g.basis("a complete specification must fully describe the invention and end with claims",
                  "contents of complete specification claims abstract"),
        "- Information on corresponding foreign applications will be furnished and kept updated."
        + g.basis("the applicant must disclose foreign filing information",
                  "statement and undertaking regarding foreign applications section 8"),
        "- The source and geographical origin of any biological material used in the "
        "invention is disclosed in the specification."
        + g.basis("the source and geographical origin of biological material must be disclosed",
                  "disclosure source geographical origin biological material specification"),
        "",
        "### Note on patentability exclusions",
        "",
        "The claims are drafted to avoid the exclusions in Section 3 — in particular "
        "mere admixture (3(e)) and traditional knowledge / aggregation of known "
        "properties (3(p))."
        + g.basis("Section 3 lists what are not inventions",
                  "what are not inventions section 3 traditional knowledge admixture"),
        "See the separate Section 3(p)/3(e) argument draft if an objection is raised.",
    ]
    return body


def _nba_abs(matter: Matter, g: _Grounder) -> list[str]:
    p = matter.profile
    return [
        "## Application to the National Biodiversity Authority",
        "_(Biological Diversity Act, 2002 — approval / intimation before applying "
        "for IP on a biological resource)_",
        "",
        "1. **Applicant:** [name, nationality, address]",
        "2. **Whether Indian / non-Indian / body corporate with foreign participation:** [ ]",
        "3. **Biological resource(s) involved:** "
        + (", ".join(p.key_ingredients) if p.key_ingredients else "[species / material]"),
        f"4. **Source and geographical origin:** {p.source_notes or '[state / district, collector]'}",
        f"5. **Purpose:** IP application for '{matter.formulation_label or matter.title}'"
        f" — {p.intended_use or '[intended use]'}",
        "6. **Associated traditional knowledge used:** [yes / no — describe]",
        "",
        "### Legal basis",
        "",
        "- Approval of / intimation to the NBA is required before applying for any IP "
        "based on research on a biological resource obtained from India."
        + g.basis("NBA approval is needed before applying for IP on a biological resource",
                  "approval National Biodiversity Authority before applying intellectual property right biological resource"),
        "- Obtaining the biological resource for research or commercial utilisation "
        "requires prior approval."
        + g.basis("prior approval is needed to obtain biological resources for research or commercial use",
                  "prior approval obtain biological resource research commercial utilisation"),
        "- Benefit-sharing terms will be as mutually agreed and as determined by the NBA."
        + g.basis("benefit sharing is determined by the NBA on mutually agreed terms",
                  "determination of equitable benefit sharing mutually agreed terms"),
        "",
        "_Note: the Biological Diversity Act was amended in 2023; confirm which "
        "regime (approval vs. intimation) applies to this applicant class._",
    ]


def _disclosure_of_source(matter: Matter, g: _Grounder) -> list[str]:
    p = matter.profile
    return [
        "## Declaration — source and geographical origin of biological material",
        "",
        "In respect of the patent application for "
        f"**{matter.formulation_label or matter.title}**, the applicant declares:",
        "",
        "1. **Biological material used in the invention:** "
        + (", ".join(p.key_ingredients) if p.key_ingredients else "[material]"),
        f"2. **Source:** {p.source_notes or '[supplier / collection]'}",
        "3. **Geographical origin:** [country / state / district]",
        "4. **Whether obtained from India:** [yes / no]",
        "5. **NBA approval / intimation reference (if applicable):** [number, date]",
        "",
        "### Legal basis",
        "",
        "- The complete specification must disclose the source and geographical "
        "origin of the biological material."
        + g.basis("disclosure of source and geographical origin is mandatory in the specification",
                  "disclosure source geographical origin biological material specification"),
        "- Non-disclosure or wrongful mention of the source is a ground for "
        "pre-grant / post-grant opposition and for revocation."
        + g.basis("non-disclosure of the biological source is a ground of opposition and revocation",
                  "opposition revocation non disclosure wrongful mention biological material source"),
        "",
        "_Signature / date / place — to be completed by the applicant._",
    ]


def _s3p_rebuttal(matter: Matter, g: _Grounder) -> list[str]:
    p = matter.profile
    novelty = p.process_novelty or (
        "[state the technical advance — new process, novel extract, unexpected "
        "synergy, or new therapeutic effect]"
    )
    return [
        "## Submission — the claimed invention is not excluded under Section 3(p) / 3(e)",
        "",
        f"Re: examination of the application for **{matter.formulation_label or matter.title}**.",
        "",
        "### The exclusions relied on",
        "",
        "- Section 3(p) excludes an invention which is, in effect, traditional "
        "knowledge or an aggregation / duplication of known properties of "
        "traditionally known component(s)."
        + g.basis("Section 3(p) excludes traditional knowledge",
                  "traditional knowledge aggregation duplication known properties section 3(p)"),
        "- Section 3(e) excludes a substance obtained by mere admixture resulting "
        "only in the aggregation of the properties of its components."
        + g.basis("Section 3(e) excludes mere admixture",
                  "substance mere admixture aggregation properties components section 3(e)"),
        "",
        "### Why the claims fall outside these exclusions",
        "",
        f"1. **The technical contribution is not merely additive.** {novelty}",
        "2. **The effect is not a known property of the components.** [cite the "
        "comparative data / unexpected result in the specification].",
        "3. **The claim is to a specific process / composition, not to the "
        "traditionally known use.** [identify the claim(s)].",
        "4. **No single prior-art source discloses the claimed combination with "
        "the demonstrated effect.** [TKDL / prior-art search to be annexed — the "
        "assistant's TKDL cross-check is not yet connected].",
        "",
        "### Requested outcome",
        "",
        "Withdrawal of the Section 3(p) / 3(e) objection, or a hearing.",
    ]


_TEMPLATES = {
    DraftKind.form1: _form1,
    DraftKind.nba_abs: _nba_abs,
    DraftKind.disclosure_of_source: _disclosure_of_source,
    DraftKind.s3p_rebuttal: _s3p_rebuttal,
}


def render(matter: Matter, kind: DraftKind) -> RenderedDraft:
    info = KIND_INFO[kind]
    g = _Grounder(matter.jurisdiction.value)
    body = _TEMPLATES[kind](matter, g)
    lines = _header(matter, info.title) + body + _traceability(g)
    return RenderedDraft(
        kind=kind,
        title=info.title,
        markdown="\n".join(lines) + "\n",
        citations=list(g.used),
    )
